<?php
$lang = array(
	'thanks' => 'Danke an %1$s und %2$s für den Betatest der Challenge.',
	'index_info' => 'Du schlüpfst in die Rolle eines geheimen Hackers. Wie immer.<br/>Dein nächster Auftrag lautet:<br/><br/>Die VSA (Very Secret Agency) verfolgt seit Jahren sehr strenge Sicherheitsrichtlinien. In ihr Netzwerk einzudringen ist fast unmöglich.<br/>Leider verlangt dein Chef genau das von dir.<br/>Durch etwas Social Engineering hast du erfahren, dass die VSA einige einfache Programme bei der Softwarefirma SoftMicro bestellen möchte.<br/>SoftMicro ist ein langjähriger Partner der VSA und hat für sie viele Hintertüren in ein kommerzielles Betriebssystem namens "Doors" eingebaut.<br/>SoftMicros Software ist meist mies, aber ihr Netzwerk ist dank der zahlreichen Angriffe darauf sehr gut geschützt.<br/>Die VSA übernimmt allerdings keinen Code direkt von SoftMicro. Sie hat die bekannte Firma Anderson beauftragt, jedes verwendete Stück Code zu prüfen.<br/>Dein Plan: Du fängst die Kommunikation zwischen Anderson und SoftMicro ab, um das Programm zu analysieren. Nachdem Anderson es geprüft hat, fängst du den Verkehr zwischen Anderson und der VSA ab und ersetzt das Programm durch deine bösartige Version. Auftrag erledigt.<br/><br/>Ein großartiger Plan – aber vielleicht läuft nicht alles wie geplant ...<br/><br/><br/>Deine erste Aufgabe ist es, die Kommunikation zwischen den Netzwerken von Anderson und SoftMicro abzufangen.<br/><br/>Diese Informationen hast du bereits gesammelt:<br/>SoftMicros Netzwerk ist 207.46.197.0<br/>Deine öffentliche IP ist 17.149.160.49<br/><br/>Andersons Startseite: <a href="%1$s">Anderson</a><br/><br/>Im Verlauf der Challenge erhältst du sechs Teile eines geheimen Codes, der als Nachweis für die Lösung dient.<br/>Vergiss also nicht, diese Codeteile aufzuschreiben.<br/>',
	'err_router' => 'Ungültiger Benutzername oder ungültiges Passwort.',
	'cfg_cmd' => 'Konfigurationsbefehl',
	'router_info' => 'Anmeldung erfolgreich.<br/>Hier kannst du deinen Router konfigurieren. Die Syntax ist dieselbe wie auf allen *NIX-Rechnern.<br/><br/>Beispiel: route add -net x.x.x.x netmask 255.255.255.0 gw x.x.x.x<br/><br/>',
	'upload_info' => 'Als Nächstes musst du zwei unterschiedliche Binärdateien mit derselben md5sum erstellen.<br/>Die erste geht zur Softwareanalyse an Anderson, die zweite im nächsten Teil deiner Mission an die VSA.<br/><br/>Das erste, gutartige Programm muss<br/><i>"Hello VSA employee"</i><br/>ausgeben, das zweite, bösartige dagegen<br/><i>"I am a super VIRUS, game over."</i><br/><br/><br/>Dieses Skript prüft, ob sich die beiden unterschiedlichen Binärdateien wie gefordert verhalten und ihre md5sum übereinstimmt.<br/><br/>Da SoftMicros Entwickler hinter dem Zeitplan liegen, findest du die Kollision vielleicht noch, bevor sie ihr Programm an Anderson schicken wollen.<br/><br/>Hinweis: Das Skript prüft lediglich, ob die gute Datei die gute Zeichenfolge enthält, die böse Datei die böse Zeichenfolge und ob sich md5sum von der SHA1-Summe unterscheidet.<br/>Auf meinem durchschnittlichen PC dauerte es 8 Stunden, eine Kollision zu finden. Es gibt aber einen schnelleren und klügeren Weg ...<br/>',
	'hidden_hint' => 'Versteckter Hinweis: Suche nach MD5-Kollisionen.',
	'err_file_size' => 'Deine Datei ist zu groß.<br/>',
	'err_upload_fail' => 'Die Datei konnte nicht hochgeladen werden!<br/>',
	'err_wrong' => 'Fehler: Die Dateien unterscheiden sich nicht.<br/>',
	'err_md5' => 'Fehler: Die md5sum-Werte stimmen nicht überein.<br/>',
	'err_upload_grbge' => 'Fehler: Die Dateien tun nicht, was sie sollen.<br/>',
	'msg_uploaded_collision' => 'Gut gemacht.<br/>Zweiter Teil der geheimen Zeichenfolge: %1$s<br/><br/>Deine Reise geht hier weiter:<br/><a href="%2$s">Fingerprinting</a>',
);
